# Pre-commit hooks
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(workflows/|ComfyUI/)
      - id: end-of-file-fixer
        exclude: ^(workflows/|ComfyUI/)
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
        exclude: ^(workflows/|ComfyUI/)
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
